# Generated by Django 4.1.4 on 2023-01-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
