# Generated by Django 4.1.4 on 2022-12-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='username',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
