# Generated by Django 4.1.4 on 2023-01-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='Token',
            field=models.TextField(null=True),
        ),
    ]
